'use client';
import {useEffect,useState} from 'react';
import {ArrowRight,BookOpen,CalendarCheck,CheckCircle2,Globe2,MapPin,Wallet,CreditCard,Languages,Menu,ShieldCheck} from 'lucide-react';

type Task={id:number;title:string;category:string;done:boolean};
const initialTasks:Task[]=[{id:1,title:'Prepare passport copy',category:'Documents',done:false},{id:2,title:'Check visa requirements',category:'Visa',done:false},{id:3,title:'Confirm dormitory',category:'Dormitory',done:false},{id:4,title:'Prepare Korean basics',category:'Korean',done:false}];
export default function Home(){
 const [tasks,setTasks]=useState<Task[]>(initialTasks); const [tab,setTab]=useState('Dashboard'); const [amount,setAmount]=useState(''); const [balance,setBalance]=useState(0); const [lang,setLang]=useState('English');
 useEffect(()=>{const t=localStorage.getItem('gks-tasks');if(t)setTasks(JSON.parse(t));const b=localStorage.getItem('gks-balance');if(b)setBalance(Number(b));},[]);
 const saveTasks=(next:Task[])=>{setTasks(next);localStorage.setItem('gks-tasks',JSON.stringify(next))};
 const addExpense=()=>{const n=Number(amount);if(!n)return;const next=balance-n;setBalance(next);localStorage.setItem('gks-balance',String(next));setAmount('')};
 const done=tasks.filter(t=>t.done).length; const progress=Math.round(done/tasks.length*100);
 const nav=['Dashboard','Checklist','University','Finance','Academics','Korean','Documents','Map','Emergency'];
 return <main className="min-h-screen"><div className="flex min-h-screen">
  <aside className="hidden md:flex w-64 shrink-0 flex-col border-r border-white/10 p-5 bg-slate-950/70 sticky top-0 h-screen">
   <div className="mb-8"><div className="text-xl font-bold">GKS Campus Bridge</div><div className="text-xs muted mt-1">Your bridge to life in Korea.</div></div>
   <div className="space-y-1">{nav.map(n=><button key={n} onClick={()=>setTab(n)} className={`w-full text-left px-3 py-2.5 rounded-xl text-sm ${tab===n?'bg-white/10':'hover:bg-white/5'}`}>{n}</button>)}</div>
   <div className="mt-auto text-xs muted flex gap-2"><ShieldCheck size={15}/> Demo-safe local data</div>
  </aside>
  <section className="flex-1 p-4 md:p-8 max-w-7xl mx-auto w-full">
   <header className="flex items-center justify-between mb-7"><div><div className="text-sm muted">GKS Journey</div><h1 className="text-2xl md:text-3xl font-bold">{tab}</h1></div><div className="flex gap-2"><button onClick={()=>setLang(lang==='English'?'Русский':'English')} className="card px-3 py-2 text-sm flex gap-2 items-center"><Globe2 size={16}/>{lang}</button><button className="md:hidden card p-2"><Menu size={20}/></button></div></header>
   {tab==='Dashboard'&&<>
    <div className="grid md:grid-cols-3 gap-4 mb-5"><div className="card glass p-5 md:col-span-2"><div className="flex justify-between"><div><div className="muted text-sm">Current stage</div><div className="text-xl font-semibold mt-1">Pre-departure</div></div><div className="text-2xl font-bold">{progress}%</div></div><div className="h-2 bg-slate-800 rounded-full mt-6"><div className="h-2 rounded-full bg-white" style={{width:`${progress}%`}}/></div><div className="flex justify-between mt-3 text-xs muted"><span>GKS Winner</span><span>University</span><span>Graduation</span></div></div>
     <div className="card p-5"><div className="muted text-sm">University</div><div className="font-semibold mt-2">Not selected</div><div className="text-xs muted mt-2">Complete onboarding to personalize this card.</div></div></div>
    <div className="grid sm:grid-cols-2 lg:grid-cols-4 gap-4 mb-5">{[[CalendarCheck,'Upcoming deadlines','Add your first deadline'],[Wallet,'Finance',`₩${balance.toLocaleString()}`],[Languages,'Korean Helper','Translate for Korea'],[MapPin,'Student Map','Find nearby places']].map(([Icon,title,value]:any)=><button key={title} onClick={()=>setTab(title==='Finance'?'Finance':title==='Korean Helper'?'Korean':title==='Student Map'?'Map':'Checklist')} className="card p-5 text-left hover:border-white/30"><Icon size={20}/><div className="font-semibold mt-4">{title}</div><div className="muted text-sm mt-1">{value}</div></button>)}</div>
    <div className="grid lg:grid-cols-2 gap-4"><div className="card p-5"><div className="flex justify-between mb-4"><h2 className="font-semibold">Today’s tasks</h2><button className="text-sm underline" onClick={()=>setTab('Checklist')}>View all</button></div>{tasks.slice(0,3).map(t=><div key={t.id} className="flex items-center gap-3 py-2"><CheckCircle2 size={18} className={t.done?'text-emerald-400':'text-slate-500'}/><span className={t.done?'line-through muted':''}>{t.title}</span></div>)}</div><div className="card p-5"><h2 className="font-semibold">AI Assistant</h2><p className="muted text-sm mt-2">Ask for a personalized next-step plan based on your GKS stage, tasks and deadlines.</p><button onClick={()=>alert('AI API is intentionally not connected in this starter. Add a server-side provider key before enabling it.')} className="mt-5 px-4 py-2 rounded-xl bg-white text-slate-950 text-sm font-semibold">Open AI Assistant <ArrowRight size={16} className="inline ml-1"/></button></div></div>
   </>}
   {tab==='Checklist'&&<div className="card p-5"><h2 className="font-semibold mb-4">Pre-departure checklist</h2>{tasks.map(t=><label key={t.id} className="flex items-center gap-3 py-3 border-b border-white/5"><input type="checkbox" checked={t.done} onChange={()=>saveTasks(tasks.map(x=>x.id===t.id?{...x,done:!x.done}:x))}/><span className={t.done?'line-through muted':''}>{t.title}</span><span className="ml-auto text-xs muted">{t.category}</span></label>)}</div>}
   {tab==='Finance'&&<div className="grid md:grid-cols-2 gap-4"><div className="card p-6"><div className="muted">Available balance</div><div className="text-3xl font-bold mt-2">₩{balance.toLocaleString()}</div><div className="flex gap-2 mt-5"><input value={amount} onChange={e=>setAmount(e.target.value)} placeholder="Expense amount" inputMode="numeric" className="flex-1 rounded-xl bg-slate-900 border border-white/10 px-3"/><button onClick={addExpense} className="px-4 rounded-xl bg-white text-slate-950">Add</button></div></div><div className="card p-6"><h2 className="font-semibold">Data status</h2><p className="muted text-sm mt-2">No GKS payment assumptions are included. Connect verified sources and store effective dates before publishing scholarship figures.</p></div></div>}
   {['University','Academics','Documents','Map'].includes(tab)&&<div className="card p-8"><div className="flex items-center gap-3"><BookOpen/><h2 className="text-xl font-semibold">{tab}</h2></div><p className="muted mt-3">This module is scaffolded. Connect its real provider/database layer before using live data. The UI intentionally does not invent university, map or document information.</p></div>}
   {tab==='Korean'&&<div className="card p-6"><h2 className="text-xl font-semibold">Translate for Korea</h2><textarea placeholder="Type a phrase..." className="mt-4 w-full min-h-32 rounded-xl bg-slate-900 border border-white/10 p-3"/><button onClick={()=>alert('Translation provider is not connected in this starter.')} className="mt-3 px-4 py-2 rounded-xl bg-white text-slate-950">Translate</button></div>}
   {tab==='Emergency'&&<div className="card p-6 border-red-400/20"><h2 className="text-2xl font-bold">Emergency Mode</h2><p className="muted mt-2">This starter does not hard-code emergency contacts. Add verified official sources before production deployment.</p></div>}
  </section></div><div className="md:hidden fixed bottom-0 left-0 right-0 bg-slate-950/95 border-t border-white/10 flex justify-around p-2">{['Dashboard','Checklist','Finance','Korean','Map'].map(n=><button key={n} onClick={()=>setTab(n)} className="text-xs px-2 py-2">{n}</button>)}</div></main>
}
